#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE)
#define CFG_TUSB_OS OPT_OS_PICO

#define CFG_TUD_ENABLED 1

#ifdef RP2350_USB_CDC_ONLY
#define CFG_TUD_AUDIO 0
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_CDC_MIDI_TEST)
#define CFG_TUD_AUDIO 0
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 1
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
#define CFG_TUD_AUDIO 2
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_MIC_CDC_TEST)
#define CFG_TUD_AUDIO 1
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_SPK_CDC_TEST)
#define CFG_TUD_AUDIO 1
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
#define CFG_TUD_AUDIO 2
#define CFG_TUD_CDC 2
#define CFG_TUD_MIDI 1
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
#define CFG_TUD_AUDIO 2
#define CFG_TUD_CDC 2
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
#define CFG_TUD_AUDIO 2
#define CFG_TUD_CDC 0
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
#define CFG_TUD_AUDIO 1
#define CFG_TUD_CDC 0
#define CFG_TUD_MIDI 0
#elif defined(RP2350_USB_MIDI_ONLY)
#define CFG_TUD_AUDIO 0
#define CFG_TUD_CDC 0
#define CFG_TUD_MIDI 1
#else
#define CFG_TUD_AUDIO 1
#define CFG_TUD_CDC 1
#define CFG_TUD_MIDI 1
#endif

#define CFG_TUD_ENDPOINT0_SIZE 64

#define CFG_TUD_CDC_RX_BUFSIZE 64
#define CFG_TUD_CDC_TX_BUFSIZE 64

#define CFG_TUD_MIDI_RX_BUFSIZE 64
#define CFG_TUD_MIDI_TX_BUFSIZE 64

#ifdef RP2350_USB_AUDIO_CDC_TEST
#define RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)
#define CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE 48000
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN TUD_AUDIO_MIC_ONE_CH_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX 2
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX 1

#define CFG_TUD_AUDIO_FUNC_2_SAMPLE_RATE 48000
#define CFG_TUD_AUDIO_FUNC_2_DESC_LEN RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_2_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_2_CTRL_BUF_SZ 64
#define CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_RX 2
#define CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_RX 1

#define CFG_TUD_AUDIO_EP_SZ_IN TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX)
#define CFG_TUD_AUDIO_EP_SZ_OUT TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_2_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_RX)

#define CFG_TUD_AUDIO_ENABLE_EP_IN 1
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1

#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX CFG_TUD_AUDIO_EP_SZ_IN
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ CFG_TUD_AUDIO_EP_SZ_IN
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX 0
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ 0

#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX 0
#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SW_BUF_SZ 0
#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SZ_MAX CFG_TUD_AUDIO_EP_SZ_OUT
#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SW_BUF_SZ CFG_TUD_AUDIO_EP_SZ_OUT
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY) || defined(RP2350_USB_AUDIO_DUPLEX_CDC) || defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
// Function 1: the already proven stereo RX speaker with asynchronous feedback.
#define CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE 48000
#define RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX 2
#define CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX 16
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 2

// Function 2: a mono TX microphone. It deliberately sends silence until the
// WM8960 ADC/I2S receive path is implemented.
#define CFG_TUD_AUDIO_FUNC_2_SAMPLE_RATE 48000
#define CFG_TUD_AUDIO_FUNC_2_DESC_LEN TUD_AUDIO_MIC_ONE_CH_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_2_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_2_CTRL_BUF_SZ 64
#define CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX 2
#define CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_TX 1

#define CFG_TUD_AUDIO_EP_SZ_OUT TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)
#define CFG_TUD_AUDIO_EP_SZ_IN TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_2_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_TX)

#define CFG_TUD_AUDIO_ENABLE_EP_IN 1
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 1
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION 0

#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX 0
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ 0
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX CFG_TUD_AUDIO_EP_SZ_OUT
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ (8 * CFG_TUD_AUDIO_EP_SZ_OUT)

#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX CFG_TUD_AUDIO_EP_SZ_IN
#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SW_BUF_SZ (2 * CFG_TUD_AUDIO_EP_SZ_IN)
#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SZ_MAX 0
#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SW_BUF_SZ 0
#else
#define CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE 48000
#define RP2350_TUD_AUDIO_HEADSET_MONO_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN * 2 + TUD_AUDIO_DESC_OUTPUT_TERM_LEN * 2 + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 4 + TUD_AUDIO_DESC_CS_AS_INT_LEN * 2 + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN * 2 + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN * 2 + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN * 2)
#ifdef RP2350_USB_AUDIO_OUT_ONLY
#define RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#elif defined(RP2350_USB_SPK_CDC_TEST)
#define RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#elif defined(RP2350_USB_MIC_CDC_TEST)
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN TUD_AUDIO_MIC_ONE_CH_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#else
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN RP2350_TUD_AUDIO_HEADSET_MONO_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 2
#endif
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64

#if defined(RP2350_USB_SPK_CDC_TEST) || defined(RP2350_USB_AUDIO_OUT_ONLY)
#define CFG_TUD_AUDIO_ENABLE_EP_IN 0
#else
#define CFG_TUD_AUDIO_ENABLE_EP_IN 1
#endif
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1

// Microphone (IN)
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX 2
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX 1
#define CFG_TUD_AUDIO_EP_SZ_IN TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX)
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX CFG_TUD_AUDIO_EP_SZ_IN
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ CFG_TUD_AUDIO_EP_SZ_IN

// Speaker (OUT)
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX 2
#define CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX 16
#ifdef RP2350_USB_AUDIO_OUT_ONLY
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 2
#else
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 1
#endif
#ifdef RP2350_USB_AUDIO_OUT_ONLY
#define CFG_TUD_AUDIO_EP_SZ_OUT TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)
#else
#define CFG_TUD_AUDIO_EP_SZ_OUT TUD_AUDIO_EP_SIZE(CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)
#endif
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX CFG_TUD_AUDIO_EP_SZ_OUT
#if defined(RP2350_USB_SPK_CDC_TEST) || defined(RP2350_USB_AUDIO_OUT_ONLY)
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ (4 * CFG_TUD_AUDIO_EP_SZ_OUT)
#else
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ CFG_TUD_AUDIO_EP_SZ_OUT
#endif

#ifdef RP2350_USB_AUDIO_OUT_ONLY
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 1
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION 0
#endif

// Audio Function 2 (speaker)
#define CFG_TUD_AUDIO_FUNC_2_SAMPLE_RATE 48000
#define CFG_TUD_AUDIO_FUNC_2_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)
#define CFG_TUD_AUDIO_FUNC_2_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_2_CTRL_BUF_SZ 64
#define CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX 2
#define CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_TX 1
#define CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_RX 2
#define CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_RX 1

#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX 0
#define CFG_TUD_AUDIO_FUNC_2_EP_IN_SW_BUF_SZ 0

#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SZ_MAX CFG_TUD_AUDIO_EP_SZ_OUT
#define CFG_TUD_AUDIO_FUNC_2_EP_OUT_SW_BUF_SZ CFG_TUD_AUDIO_EP_SZ_OUT
#endif

#ifdef __cplusplus
}
#endif

#endif
