#include "tusb.h"
#include <string.h>

#include "usb_os_guessing.h"

#ifdef RP2350_USB_CDC_ONLY
enum {
    ITF_NUM_CDC = 0,
    ITF_NUM_CDC_DATA,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_CDC_NOTIF = 0x81,
    EPNUM_CDC_OUT   = 0x01,
    EPNUM_CDC_IN    = 0x82,
};
#elif defined(RP2350_USB_CDC_MIDI_TEST)
enum {
    ITF_NUM_CDC = 0,
    ITF_NUM_CDC_DATA,
    ITF_NUM_MIDI,
    ITF_NUM_MIDI_STREAMING,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_CDC_NOTIF = 0x81,
    EPNUM_CDC_OUT   = 0x01,
    EPNUM_CDC_IN    = 0x82,
    EPNUM_MIDI_OUT  = 0x02,
    EPNUM_MIDI_IN   = 0x83,
};
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
enum {
    ITF_NUM_AUDIO_SPK_CONTROL = 0,
    ITF_NUM_AUDIO_SPK_STREAMING,
    ITF_NUM_AUDIO_MIC_CONTROL,
    ITF_NUM_AUDIO_MIC_STREAMING,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_IN  = 0x81,
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_AUDIO_FB  = 0x82,
    EPNUM_CDC_NOTIF = 0x83,
    EPNUM_CDC_OUT   = 0x04,
    EPNUM_CDC_IN    = 0x84,
};
#elif defined(RP2350_USB_MIC_CDC_TEST)
enum {
    ITF_NUM_AUDIO_CONTROL = 0,
    ITF_NUM_AUDIO_STREAMING_MIC,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_IN  = 0x81,
    EPNUM_CDC_NOTIF = 0x82,
    EPNUM_CDC_OUT   = 0x03,
    EPNUM_CDC_IN    = 0x83,
};
#elif defined(RP2350_USB_SPK_CDC_TEST)
enum {
    ITF_NUM_AUDIO_CONTROL = 0,
    ITF_NUM_AUDIO_STREAMING_SPK,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_CDC_NOTIF = 0x82,
    EPNUM_CDC_OUT   = 0x03,
    EPNUM_CDC_IN    = 0x83,
};
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
enum {
    ITF_NUM_AUDIO_SPK_CONTROL = 0,
    ITF_NUM_AUDIO_SPK_STREAMING,
    ITF_NUM_AUDIO_MIC_CONTROL,
    ITF_NUM_AUDIO_MIC_STREAMING,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_CONSOLE_CDC,
    ITF_NUM_CONSOLE_CDC_DATA,
    ITF_NUM_MIDI,
    ITF_NUM_MIDI_STREAMING,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_AUDIO_FB  = 0x81,
    EPNUM_AUDIO_IN  = 0x82,
    EPNUM_CDC_NOTIF = 0x83,
    EPNUM_CDC_OUT   = 0x03,
    EPNUM_CDC_IN    = 0x84,
    EPNUM_MIDI_OUT  = 0x05,
    EPNUM_MIDI_IN   = 0x85,
    EPNUM_CONSOLE_OUT   = 0x06,
    EPNUM_CONSOLE_IN    = 0x86,
    EPNUM_CONSOLE_NOTIF = 0x87,
};
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
enum {
    ITF_NUM_AUDIO_SPK_CONTROL = 0,
    ITF_NUM_AUDIO_SPK_STREAMING,
    ITF_NUM_AUDIO_MIC_CONTROL,
    ITF_NUM_AUDIO_MIC_STREAMING,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_CONSOLE_CDC,
    ITF_NUM_CONSOLE_CDC_DATA,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_AUDIO_FB  = 0x81,
    EPNUM_AUDIO_IN  = 0x82,
    EPNUM_CDC_NOTIF = 0x83,
    EPNUM_CDC_OUT   = 0x03,
    EPNUM_CDC_IN    = 0x84,
    EPNUM_CONSOLE_OUT   = 0x06,
    EPNUM_CONSOLE_IN    = 0x86,
    EPNUM_CONSOLE_NOTIF = 0x87,
};
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
enum {
    ITF_NUM_AUDIO_SPK_CONTROL = 0,
    ITF_NUM_AUDIO_SPK_STREAMING,
    ITF_NUM_AUDIO_MIC_CONTROL,
    ITF_NUM_AUDIO_MIC_STREAMING,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_AUDIO_FB  = 0x81,
    EPNUM_AUDIO_IN  = 0x82,
};
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
enum {
    ITF_NUM_AUDIO_CONTROL = 0,
    ITF_NUM_AUDIO_STREAMING_SPK,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_AUDIO_FB  = 0x81,
};
#elif defined(RP2350_USB_MIDI_ONLY)
enum {
    ITF_NUM_MIDI = 0,
    ITF_NUM_MIDI_STREAMING,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_MIDI_OUT = 0x01,
    EPNUM_MIDI_IN  = 0x81,
};
#else
enum {
    ITF_NUM_AUDIO_CONTROL = 0,
    ITF_NUM_AUDIO_SPK_STREAMING,
    ITF_NUM_AUDIO_MIC_STREAMING,
    ITF_NUM_CDC,
    ITF_NUM_CDC_DATA,
    ITF_NUM_MIDI,
    ITF_NUM_MIDI_STREAMING,
    ITF_NUM_TOTAL
};

enum {
    EPNUM_AUDIO_IN  = 0x81,
    EPNUM_AUDIO_OUT = 0x01,
    EPNUM_CDC_NOTIF = 0x82,
    EPNUM_CDC_OUT   = 0x03,
    EPNUM_CDC_IN    = 0x83,
    EPNUM_MIDI_OUT  = 0x04,
    EPNUM_MIDI_IN   = 0x84,
};
#endif

#if CFG_TUD_AUDIO > 0
#ifndef RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN
#define RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)
#endif

#define RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESCRIPTOR(_itfnum, _stridx, _epout, _epsize, _bytes_per_sample, _sync_type, _cs_ep_attr) \
    TUD_AUDIO_DESC_IAD(_itfnum, 0x02, 0x00), \
    TUD_AUDIO_DESC_STD_AC(_itfnum, 0x00, _stridx), \
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_DESKTOP_SPEAKER, \
        TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN, \
        AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO_DESC_CLK_SRC(0x04, AUDIO_CLOCK_SOURCE_ATT_INT_FIX_CLK, \
        AUDIO_CTRL_R << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, 0x01, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(0x01, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, 0x04, 0x01, \
        AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0, 0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(0x03, AUDIO_TERM_TYPE_OUT_DESKTOP_SPEAKER, 0x01, 0x02, 0x04, 0x0000, 0x00), \
    TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL(0x02, 0x01, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 1, 0x00, 0x00, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 1, 0x01, 0x01, 0x00), \
    TUD_AUDIO_DESC_CS_AS_INT(0x01, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, \
        AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x01, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT(_bytes_per_sample, (_bytes_per_sample) * 8), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, \
        (uint8_t)(TUSB_XFER_ISOCHRONOUS | (_sync_type) | TUSB_ISO_EP_ATT_DATA), _epsize, 0x01), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP(_cs_ep_attr, AUDIO_CTRL_NONE, \
        AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)

#define RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + TUD_AUDIO_DESC_STD_AS_INT_LEN * 2 + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)

#define RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(_itfnum, _stridx, _bytes_per_sample, _bits_per_sample, _epout, _epoutsize, _epfb, _epfbsize) \
    TUD_AUDIO_DESC_IAD(_itfnum, 0x02, 0x00), \
    TUD_AUDIO_DESC_STD_AC(_itfnum, 0x00, _stridx), \
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_DESKTOP_SPEAKER, \
        TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN, \
        AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO_DESC_CLK_SRC(0x04, AUDIO_CLOCK_SOURCE_ATT_INT_PRO_CLK, \
        AUDIO_CTRL_RW << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, 0x01, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(0x01, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, 0x04, 0x02, \
        AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0, 0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(0x03, AUDIO_TERM_TYPE_OUT_DESKTOP_SPEAKER, 0x01, 0x02, 0x04, 0x0000, 0x00), \
    TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL(0x02, 0x01, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT((_itfnum) + 1, 0x00, 0x00, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT((_itfnum) + 1, 0x01, 0x02, 0x00), \
    TUD_AUDIO_DESC_CS_AS_INT(0x01, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, \
        AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT(_bytes_per_sample, _bits_per_sample), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, \
        (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), \
        _epoutsize, 0x01), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, \
        AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001), \
    TUD_AUDIO_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, 0x01)

// One UAC2 function containing both mono speaker and mono microphone.
#define RP2350_TUD_AUDIO_HEADSET_MONO_DESCRIPTOR(_itfnum, _stridx_spk, _stridx_mic, _epout, _epin) \
    TUD_AUDIO_DESC_IAD(_itfnum, 0x03, 0x00), \
    TUD_AUDIO_DESC_STD_AC(_itfnum, 0x00, _stridx_spk), \
    TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_HEADSET, \
        TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN * 2 + TUD_AUDIO_DESC_OUTPUT_TERM_LEN * 2 + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN, \
        AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO_DESC_CLK_SRC(0x04, AUDIO_CLOCK_SOURCE_ATT_INT_FIX_CLK, \
        AUDIO_CTRL_R << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, 0x01, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(0x01, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, 0x04, 0x01, \
        AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0, 0x00), \
    TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL(0x02, 0x01, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, \
        AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(0x03, AUDIO_TERM_TYPE_OUT_HEADPHONES, 0x00, 0x02, 0x04, 0x0000, 0x00), \
    TUD_AUDIO_DESC_INPUT_TERM(0x11, AUDIO_TERM_TYPE_IN_GENERIC_MIC, 0x00, 0x04, 0x01, \
        AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0, 0x00), \
    TUD_AUDIO_DESC_OUTPUT_TERM(0x13, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, 0x11, 0x04, 0x0000, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 1, 0x00, 0x00, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 1, 0x01, 0x01, _stridx_spk), \
    TUD_AUDIO_DESC_CS_AS_INT(0x01, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, \
        AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x01, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX * 8), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ADAPTIVE | TUSB_ISO_EP_ATT_DATA), CFG_TUD_AUDIO_EP_SZ_OUT, 0x01), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, \
        AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 2, 0x00, 0x00, 0x00), \
    TUD_AUDIO_DESC_STD_AS_INT(_itfnum + 2, 0x01, 0x01, _stridx_mic), \
    TUD_AUDIO_DESC_CS_AS_INT(0x13, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, \
        AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x01, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX * 8), \
    TUD_AUDIO_DESC_STD_AS_ISO_EP(_epin, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), CFG_TUD_AUDIO_EP_SZ_IN, 0x01), \
    TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, \
        AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)
#endif

#ifdef RP2350_USB_CDC_ONLY
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_CDC_DESC_LEN)
#elif defined(RP2350_USB_CDC_MIDI_TEST)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_CDC_DESC_LEN + TUD_MIDI_DESC_LEN)
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_AUDIO_MIC_ONE_CH_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN + TUD_CDC_DESC_LEN)
#elif defined(RP2350_USB_MIC_CDC_TEST)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_AUDIO_MIC_ONE_CH_DESC_LEN + TUD_CDC_DESC_LEN)
#elif defined(RP2350_USB_SPK_CDC_TEST)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESC_LEN + TUD_CDC_DESC_LEN)
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN + TUD_AUDIO_MIC_ONE_CH_DESC_LEN + (2 * TUD_CDC_DESC_LEN) + TUD_MIDI_DESC_LEN)
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN + TUD_AUDIO_MIC_ONE_CH_DESC_LEN + (2 * TUD_CDC_DESC_LEN))
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN + TUD_AUDIO_MIC_ONE_CH_DESC_LEN)
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN)
#elif defined(RP2350_USB_MIDI_ONLY)
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_MIDI_DESC_LEN)
#else
#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + RP2350_TUD_AUDIO_HEADSET_MONO_DESC_LEN + TUD_CDC_DESC_LEN + TUD_MIDI_DESC_LEN)
#endif

static const tusb_desc_device_t desc_device = {
    .bLength = sizeof(tusb_desc_device_t),
    .bDescriptorType = TUSB_DESC_DEVICE,
    /* USB 2.01 makes the BOS request available for host-OS detection. */
    .bcdUSB = 0x0201,
#ifdef RP2350_USB_CDC_ONLY
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_CDC_MIDI_TEST)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_MIC_CDC_TEST)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_SPK_CDC_TEST)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#elif defined(RP2350_USB_MIDI_ONLY)
    .bDeviceClass = 0x00,
    .bDeviceSubClass = 0x00,
    .bDeviceProtocol = 0x00,
#else
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
#endif
    .bMaxPacketSize0 = CFG_TUD_ENDPOINT0_SIZE,

    .idVendor = 0x2E8A,
#ifdef RP2350_USB_CDC_ONLY
    .idProduct = 0x401B,
    .bcdDevice = 0x0106,
#elif defined(RP2350_USB_CDC_MIDI_TEST)
    .idProduct = 0x401C,
    .bcdDevice = 0x0107,
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
    .idProduct = 0x4027,
    .bcdDevice = 0x0120,
#elif defined(RP2350_USB_MIC_CDC_TEST)
    .idProduct = 0x4022,
    .bcdDevice = 0x0113,
#elif defined(RP2350_USB_SPK_CDC_TEST)
    .idProduct = 0x4030,
    .bcdDevice = 0x0123,
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
    .idProduct = 0x403E,
    .bcdDevice = 0x0138,
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
    .idProduct = 0x403F,
    .bcdDevice = 0x0136,
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
    .idProduct = 0x403B,
    .bcdDevice = 0x0134,
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
    .idProduct = 0x4039,
    .bcdDevice = 0x0132,
#elif defined(RP2350_USB_MIDI_ONLY)
    .idProduct = 0x401A,
    .bcdDevice = 0x0105,
#else
    .idProduct = 0x401E,
    .bcdDevice = 0x0109,
#endif

    .iManufacturer = 0x01,
    .iProduct = 0x02,
    .iSerialNumber = 0x03,

    .bNumConfigurations = 0x01,
};

uint8_t const *tud_descriptor_device_cb(void) {
    usb_os_guessing_device_descriptor();
    return (uint8_t const *)&desc_device;
}

static uint8_t desc_configuration[] = {
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0, 100),

#ifdef RP2350_USB_CDC_ONLY
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 4, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
#elif defined(RP2350_USB_CDC_MIDI_TEST)
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 4, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 5, EPNUM_MIDI_OUT, EPNUM_MIDI_IN, 64),
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
    TUD_AUDIO_MIC_ONE_CH_DESCRIPTOR(ITF_NUM_AUDIO_SPK_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX * 8,
        EPNUM_AUDIO_IN, CFG_TUD_AUDIO_EP_SZ_IN),
    RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESCRIPTOR(
        ITF_NUM_AUDIO_MIC_CONTROL, 5, EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_EP_SZ_OUT,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_RX, TUSB_ISO_EP_ATT_ADAPTIVE,
        AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK),
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 6, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
#elif defined(RP2350_USB_MIC_CDC_TEST)
    TUD_AUDIO_MIC_ONE_CH_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX * 8,
        EPNUM_AUDIO_IN, CFG_TUD_AUDIO_EP_SZ_IN),
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 5, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
#elif defined(RP2350_USB_SPK_CDC_TEST)
    RP2350_TUD_AUDIO_SPEAKER_MONO_ADAPTIVE_DESCRIPTOR(
        ITF_NUM_AUDIO_CONTROL, 4, EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_EP_SZ_OUT,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, TUSB_ISO_EP_ATT_ADAPTIVE,
        AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK),
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 5, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
    RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(
        ITF_NUM_AUDIO_SPK_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX,
        CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX,
        EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX,
        EPNUM_AUDIO_FB, 4),
    TUD_AUDIO_MIC_ONE_CH_DESCRIPTOR(
        ITF_NUM_AUDIO_MIC_CONTROL, 5,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX * 8,
        EPNUM_AUDIO_IN, CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX),
    TUD_CDC_DESCRIPTOR(
        ITF_NUM_CDC, 6, EPNUM_CDC_NOTIF, 8,
        EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
    TUD_CDC_DESCRIPTOR(
        ITF_NUM_CONSOLE_CDC, 7, EPNUM_CONSOLE_NOTIF, 8,
        EPNUM_CONSOLE_OUT, EPNUM_CONSOLE_IN, 64),
    TUD_MIDI_DESCRIPTOR(
        ITF_NUM_MIDI, 8, EPNUM_MIDI_OUT, EPNUM_MIDI_IN, 64),
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
    RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(
        ITF_NUM_AUDIO_SPK_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX,
        CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX,
        EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX,
        EPNUM_AUDIO_FB, 4),
    TUD_AUDIO_MIC_ONE_CH_DESCRIPTOR(
        ITF_NUM_AUDIO_MIC_CONTROL, 5,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX * 8,
        EPNUM_AUDIO_IN, CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX),
    TUD_CDC_DESCRIPTOR(
        ITF_NUM_CDC, 6, EPNUM_CDC_NOTIF, 8,
        EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),
    TUD_CDC_DESCRIPTOR(
        ITF_NUM_CONSOLE_CDC, 7, EPNUM_CONSOLE_NOTIF, 8,
        EPNUM_CONSOLE_OUT, EPNUM_CONSOLE_IN, 64),
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
    RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(
        ITF_NUM_AUDIO_SPK_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX,
        CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX,
        EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX,
        EPNUM_AUDIO_FB, 4),
    TUD_AUDIO_MIC_ONE_CH_DESCRIPTOR(
        ITF_NUM_AUDIO_MIC_CONTROL, 5,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX,
        CFG_TUD_AUDIO_FUNC_2_N_BYTES_PER_SAMPLE_TX * 8,
        EPNUM_AUDIO_IN, CFG_TUD_AUDIO_FUNC_2_EP_IN_SZ_MAX),
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
    RP2350_TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(
        ITF_NUM_AUDIO_CONTROL, 4,
        CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX,
        CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX,
        EPNUM_AUDIO_OUT, CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX,
        EPNUM_AUDIO_FB, 4),
#elif defined(RP2350_USB_MIDI_ONLY)
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 4, EPNUM_MIDI_OUT, EPNUM_MIDI_IN, 64),
#else
    // Microphone + speaker
    RP2350_TUD_AUDIO_HEADSET_MONO_DESCRIPTOR(ITF_NUM_AUDIO_CONTROL, 4, 5, EPNUM_AUDIO_OUT, EPNUM_AUDIO_IN),

    // CDC serial
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, 6, EPNUM_CDC_NOTIF, 8, EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),

    // MIDI
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI, 7, EPNUM_MIDI_OUT, EPNUM_MIDI_IN, 64),
#endif
};

_Static_assert(
    sizeof(desc_configuration) == CONFIG_TOTAL_LEN,
    "USB configuration descriptor length mismatch"
);

#if defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI) || \
    defined(RP2350_USB_AUDIO_DUPLEX_CDC) || \
    defined(RP2350_USB_AUDIO_DUPLEX_ONLY) || \
    defined(RP2350_USB_AUDIO_OUT_ONLY)
static void set_feedback_endpoint_packet_size(uint16_t packet_size)
{
    size_t offset = 0u;

    while (offset + 2u <= sizeof(desc_configuration)) {
        uint8_t length = desc_configuration[offset];
        if (length < 2u || offset + length > sizeof(desc_configuration)) {
            return;
        }

        if (desc_configuration[offset + 1u] == TUSB_DESC_ENDPOINT &&
            length >= 7u &&
            desc_configuration[offset + 2u] == EPNUM_AUDIO_FB) {
            desc_configuration[offset + 4u] = (uint8_t)packet_size;
            desc_configuration[offset + 5u] = (uint8_t)(packet_size >> 8);
            return;
        }

        offset += length;
    }
}
#endif

uint8_t const *tud_descriptor_configuration_cb(uint8_t index) {
    (void)index;
    usb_os_guessing_configuration_descriptor();
#if defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI) || \
    defined(RP2350_USB_AUDIO_DUPLEX_CDC) || \
    defined(RP2350_USB_AUDIO_DUPLEX_ONLY) || \
    defined(RP2350_USB_AUDIO_OUT_ONLY)
    /* macOS requires FS 10.14 feedback in a three-byte endpoint. */
    set_feedback_endpoint_packet_size(
        usb_os_guessing_get() == USB_HOST_OS_MACOS ? 3u : 4u
    );
#endif
    return desc_configuration;
}

#define BOS_USB20_EXTENSION_LENGTH 7u
#define BOS_TOTAL_LENGTH \
    (TUD_BOS_DESC_LEN + BOS_USB20_EXTENSION_LENGTH)

static const uint8_t desc_bos[] = {
    TUD_BOS_DESCRIPTOR(BOS_TOTAL_LENGTH, 1),
    0x07, TUSB_DESC_DEVICE_CAPABILITY,
    DEVICE_CAPABILITY_USB20_EXTENSION,
    0x00, 0x00, 0x00, 0x00,
};

uint8_t const *tud_descriptor_bos_cb(void)
{
    usb_os_guessing_bos_descriptor();
    return desc_bos;
}

static const char *string_desc_arr[] = {
    (const char[]){0x09, 0x04},
    "RP2350 SDR Interface",
#ifdef RP2350_USB_CDC_ONLY
    "RP2350 SDR CDC test",
    "RP2350-CDC-0006",
    "CDC",
#elif defined(RP2350_USB_CDC_MIDI_TEST)
    "RP2350 SDR CDC + MIDI test",
    "RP2350-CDC-MIDI-0007",
    "CDC",
    "RP2350 SDR MIDI",
#elif defined(RP2350_USB_AUDIO_CDC_TEST)
    "RP2350 SDR Audio + CDC test",
    "RP2350-RX-TX-CDC-0020",
    "RP2350 SDR TX Audio",
    "RP2350 SDR RX Audio",
    "CDC",
#elif defined(RP2350_USB_MIC_CDC_TEST)
    "RP2350 SDR Mic + CDC test",
    "RP2350-MIC-CDC-0013",
    "RP2350 SDR TX Audio",
    "CDC",
#elif defined(RP2350_USB_SPK_CDC_TEST)
    "RP2350 SDR RX Audio + CDC",
    "RP2350-RX-CDC-0023",
    "RP2350 SDR RX Audio",
    "CDC",
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC_MIDI)
    "RP2350 SDR Interface",
    "RP2350-ALL-0038",
    "RP2350 SDR RX Audio",
    "RP2350 SDR TX Audio",
    "RP2350 SDR WinKey",
    "RP2350 SDR Console",
    "RP2350 SDR MIDI",
#elif defined(RP2350_USB_AUDIO_DUPLEX_CDC)
    "RP2350 SDR Interface",
    "RP2350-RXTX-CDC-0036",
    "RP2350 SDR RX Audio",
    "RP2350 SDR TX Audio",
    "RP2350 SDR WinKey",
    "RP2350 SDR Console",
#elif defined(RP2350_USB_AUDIO_DUPLEX_ONLY)
    "RP2350 SDR Audio",
    "RP2350-RXTX-AUDIO-0034",
    "RP2350 SDR RX Audio",
    "RP2350 SDR TX Audio",
#elif defined(RP2350_USB_AUDIO_OUT_ONLY)
    "RP2350 SDR RX Audio test",
    "RP2350-RX-AUDIO-0032",
    "RP2350 SDR RX Audio",
#elif defined(RP2350_USB_MIDI_ONLY)
    "RP2350 SDR MIDI",
    "RP2350-MIDI-0005",
    "RP2350 SDR MIDI",
#else
    "RP2350 SDR Interface",
    "RP2350-0009",
    "RP2350 SDR RX Audio",
    "RP2350 SDR TX Audio",
    "CDC",
    "RP2350 SDR MIDI",
#endif
};

static uint16_t _desc_str[32];

uint16_t const *tud_descriptor_string_cb(uint8_t index, uint16_t langid) {
    (void)langid;
    uint8_t chr_count;

    usb_os_guessing_string_descriptor();

    if (index == 0) {
        _desc_str[1] = 0x0409;
        chr_count = 1;
    } else {
        if (index >= (sizeof(string_desc_arr) / sizeof(string_desc_arr[0]))) {
            return NULL;
        }
        const char *str = string_desc_arr[index];
        chr_count = (uint8_t)strlen(str);
        if (chr_count > 31) {
            chr_count = 31;
        }
        for (uint8_t i = 0; i < chr_count; i++) {
            _desc_str[1 + i] = str[i];
        }
    }

    _desc_str[0] = (uint16_t)((TUSB_DESC_STRING << 8) | (2 * chr_count + 2));
    return _desc_str;
}
